// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvU8OXXR9lNkkU11S9DE6KmICFhmFgN_M',
    appId: '1:43644605158:web:018c782cc047dd3e3ea127',
    messagingSenderId: '43644605158',
    projectId: 'unvirsity-d384d',
    authDomain: 'unvirsity-d384d.firebaseapp.com',
    storageBucket: 'unvirsity-d384d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHMwbkYKOmy8MaRCu0dEqPRZ52c1Q7abU',
    appId: '1:43644605158:android:2d4ba19d23b388cc3ea127',
    messagingSenderId: '43644605158',
    projectId: 'unvirsity-d384d',
    storageBucket: 'unvirsity-d384d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkClCE60WzKDNEj-XNdfajzIxTaAe4dfE',
    appId: '1:43644605158:ios:9975d87fd45559e13ea127',
    messagingSenderId: '43644605158',
    projectId: 'unvirsity-d384d',
    storageBucket: 'unvirsity-d384d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkClCE60WzKDNEj-XNdfajzIxTaAe4dfE',
    appId: '1:43644605158:ios:9975d87fd45559e13ea127',
    messagingSenderId: '43644605158',
    projectId: 'unvirsity-d384d',
    storageBucket: 'unvirsity-d384d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvU8OXXR9lNkkU11S9DE6KmICFhmFgN_M',
    appId: '1:43644605158:web:a48370a8aaebaff03ea127',
    messagingSenderId: '43644605158',
    projectId: 'unvirsity-d384d',
    authDomain: 'unvirsity-d384d.firebaseapp.com',
    storageBucket: 'unvirsity-d384d.firebasestorage.app',
  );

}